import string

from aiogram.fsm.storage.memory import MemoryStorage

CONFIG_FILE = "botconfig.ini"

PROMOCODE_ALLOWED_SYMBOLS = set(string.ascii_letters + string.digits)

PROMOCODE_LENGTH = 16

MAX_PROMOCODE_DISCOUNT_PERCENTAGE = 50

MIN_PROMOCODE_DISCOUNT_PERCENTAGE = 5

ACCOUNT_IMAGE_ID = "AgACAgIAAxkBAAPQZPCqzEphUKVFQUbCcBSJSz9nOZgAAu7LMRv1wIFLaKxZBiAQs9UBAAMCAANzAAMwBA"

MIN_DEPOSIT_AMOUNT_RUB = 1500

MIN_WITHDRAW_AMOUNT_RUB = 1000

MAX_DEPOSIT_AMOUNT_RUB = 1000000

MAX_WITHDRAW_AMOUNT_RUB = MAX_DEPOSIT_AMOUNT_RUB

CARD_FOR_USERS_DEPOSITS_NUMBER = 2200700898861363

CARD_FOR_USERS_DEPOSITS_BANK = "Tinkoff Bank"

SUPPORT_BOT_TAG = "binance_support_trade_bot"

TRANSACTION_COMLETION_TIME_SECONDS = 900

BOT_ID = 6432965544

CUSTOM_CALLBACK_QUERIES_SEPARATOR = "@"

STATES_STORAGE = MemoryStorage

SUPPORTED_CURRENCIES = (
    "Bitcoin", "Ripple", "Doge", "Ethereum", "Binancecoin", "Litecoin", "Euro"
)

MAX_CURRENCIES_PRICES = {
    SUPPORTED_CURRENCIES[0]: 35000,
    SUPPORTED_CURRENCIES[1]: 2,
    SUPPORTED_CURRENCIES[2]: 2,
    SUPPORTED_CURRENCIES[3]: 3000,
    SUPPORTED_CURRENCIES[4]: 500,
    SUPPORTED_CURRENCIES[5]: 150,
    SUPPORTED_CURRENCIES[6]: 1.10
}

MIN_CURRENCIES_PRICES = {
    SUPPORTED_CURRENCIES[0]: 20000,
    SUPPORTED_CURRENCIES[1]: 0.25,
    SUPPORTED_CURRENCIES[2]: 0.02,
    SUPPORTED_CURRENCIES[3]: 1200,
    SUPPORTED_CURRENCIES[4]: 180,
    SUPPORTED_CURRENCIES[5]: 40,
    SUPPORTED_CURRENCIES[6]: 1
}

ALTERNATIVE_CURRENCY = "USD"

USD_RUB_RATE = 98.2

MIN_ECN_POOL_VALUE = 100

CURRENCIES_RATES_UPDATING_COOLDOWN = 5

POOL_DURATION = 30
